### ISSUE TITLE
Tabview crashes when sorting a column

### ISSUE THREAD

**Issue by doronaco** [TabViewer/tabview#168]
Reproduce

- Run `tabview raw-results.csv`
- Sort by column `short_before` by clicking `s`
Crash:
```
Traceback (most recent call last):
  File "/Users/doron/Library/Python/3.8/bin/tabview", line 108, in <module>
    view(data, enc=args.encoding, start_pos=start_pos,
  File "/Users/doron/Library/Python/3.8/lib/python/site-packages/tabview/tabview.py", line 1319, in view
    curses.wrapper(main, buf,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/curses/__init__.py", line 105, in wrapper
    return func(stdscr, *args, **kwds)
  File "/Users/doron/Library/Python/3.8/lib/python/site-packages/tabview/tabview.py", line 1250, in main
    Viewer(stdscr, *args, **kwargs).run()
  File "/Users/doron/Library/Python/3.8/lib/python/site-packages/tabview/tabview.py", line 711, in run
    self.display()
  File "/Users/doron/Library/Python/3.8/lib/python/site-packages/tabview/tabview.py", line 867, in display
    addstr(self.scr, yc, xc, s, attr)
  File "/Users/doron/Library/Python/3.8/lib/python/site-packages/tabview/tabview.py", line 37, in addstr
    return scr.addstr(*args)
_curses.error: addwstr() returned ERR
```

System:
OSX: 10.15.6 (19G2021)
tabview: 1.4.4

[raw-results.csv.zip](https://github.com/TabViewer/tabview/files/5560101/raw-results.csv.zip)

**Comment by doronaco** [comment]
looks related to https://github.com/TabViewer/tabview/issues/132
